version: '3.8'

services:
  # Go backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: servers-filters-backend
    ports:
      - "8081:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - DB_DRIVER=sqlite3
      - DB_DSN=data/servers.db
    volumes:
      - ./backend/data:/app/data
    networks:
      - servers-network

  # Vue.js frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
      args:
        - VITE_API_BASE_URL=http://localhost:8081
    container_name: servers-filters-frontend
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - servers-network


networks:
  servers-network:
    driver: bridge
