version: '3.8'

services:
  # Redis cache
  redis:
    image: redis:7-alpine
    container_name: servers-filters-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - servers-network

  # Go backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    container_name: servers-filters-backend
    ports:
      - "8081:8080"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - DB_DRIVER=sqlite3
      - DB_DSN=data/servers.db
      - CACHE_ENABLED=false
      - CACHE_TYPE=redis
      - CACHE_URL=redis://redis:6379
    volumes:
      - ./backend/data:/app/data:ro
    depends_on:
      - redis
    networks:
      - servers-network

  # Vue.js frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
    container_name: servers-filters-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_BASE_URL=http://localhost:8081
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - servers-network

volumes:
  redis_data:
    driver: local

networks:
  servers-network:
    driver: bridge
