FROM golang:1.21-alpine AS builder

RUN apk add --no-cache sqlite gcc musl-dev

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

# Copy source code
COPY . .

# Build application
RUN CGO_ENABLED=1 go build -o servers-filters main.go

FROM alpine:latest

RUN apk add --no-cache sqlite

COPY --from=builder /app/servers-filters /app/servers-filters
COPY --from=builder /app/data /app/data

WORKDIR /app

# Expose port
EXPOSE 8080

# Run the application
CMD ["./servers-filters"]
